AspNetIdentity2Permission.Mvc/Areas/SuperAdmin/Controllers/UserRoleController.cs
using AspNetIdentity2Permission.Mvc.Controllers;
using AspNetIdentity2Permission.Mvc.Models;
using AutoMapper;
using Microsoft.AspNet.Identity.EntityFramework;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web.Mvc;
using Webdiyer.WebControls.Mvc;

namespace AspNetIdentity2Permission.Mvc.Areas.SuperAdmin.Controllers
{
    [Description("用户-角色维护")]
    public class UserRoleController : BaseController
    {

        // GET: UsersAdmin
        [Description("用户列表")]
        public async Task<ActionResult> Index(int index = 1)
        {
            var users = await _userManager.Users.ToListAsync();
            var views = new List<EditUserRoleViewModel>();
            foreach (var user in users)
            {
                var view = Mapper.Map<EditUserRoleViewModel>(user);
                views.Add(view);
            }
            return View(views.ToPagedList(index, 10));
        }

        //
        //异步读取用户详情
        //GET: /Users/Details/5
        [Description("用户-角色详情")]
        public async Task<ActionResult> Details(string id)
        {
            //用户为空时返回400错误
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            //按Id查找用户
            var user = await _userManager.FindByIdAsync(id);
            var view = Mapper.Map<EditUserRoleViewModel>(user);
            ViewBag.RoleNames = await _userManager.GetRolesAsync(user.Id);

            return View(view);
        }

        //
        //异步读取用户创建
        //GET:/Users/Create
        [Description("新建用户")]
        public async Task<ActionResult> Create()
        {
            //读取角色列表
            ViewBag.RoleId = new SelectList(await _roleManager.Roles.ToListAsync(), "Name", "Name");
            return View();
        }
        //
        //异步写入用户创建
        // POST: /Users/Create
        [Description("新建用户，保存")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(RegisterViewModel userViewModel, params  string[] selectedRoles)
        {
            if (ModelState.IsValid)
            {
                var user = Mapper.Map<ApplicationUser>(userViewModel);
                var adminResult = await _userManager.CreateAsync(user, userViewModel.Password);

                //
                if (adminResult.Succeeded)
                {
                    if (selectedRoles != null)
                    {
                        var result = await _userManager.AddToRolesAsync(user.Id, selectedRoles);
                        if (!result.Succeeded)
                        {
                            ModelState.AddModelError("", result.Errors.First());
                            ViewBag.RoleId = new SelectList(await _roleManager.Roles.ToListAsync(), "Name", "Name");
                            return View();
                        }
                    }
                }
                else
                {
                    ModelState.AddModelError("", adminResult.Errors.First());
                    ViewBag.RoleId = new SelectList(_roleManager.Roles, "Name", "Name");
                    return View();
                }
                return RedirectToAction("Index");
            }
            ViewBag.RoleId = new SelectList(_roleManager.Roles, "Name", "Name");
            return View();
        }

        //
        //读取用户编辑
        // GET: /Users/Edit/1
        [Description("编辑用户-角色")]
        public async Task<ActionResult> Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var user = await _userManager.FindByIdAsync(id);
            if (user == null)
            {
                return HttpNotFound();
            }
            var userRoles = await _userManager.GetRolesAsync(user.Id);
            var view = Mapper.Map<EditUserRoleViewModel>(user);
            view.RolesList = _roleManager.Roles.ToList().Select(x => new SelectListItem()
                {
                    Selected = userRoles.Contains(x.Name),
                    Text = x.Name,
                    Value = x.Id
                });
            return View(view);
        }
        //
        //写入用户编辑
        // POST: /Users/Edit/5
        [Description("编辑用户-角色，保存")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "UserName,Email,Id")]EditUserRoleViewModel editUser, params string[] selectedRole)
        {
            if (ModelState.IsValid)
            {
                var user = await _userManager.FindByIdAsync(editUser.Id);
                if (user == null)
                {
                    return HttpNotFound();
                }
                //不允许修改用户名
                user.Email = editUser.Email;
                //更新用户信息
                var result = await _userManager.UpdateAsync(user);
                if (!result.Succeeded)
                {
                    ModelState.AddModelError("", result.Errors.First());
                    return View();
                }
                //更新角色
                //删除现有角色
                var userRoles = user.Roles.ToList();
                userRoles.ForEach(t => _db.Set<IdentityUserRole>().Remove(t));

                //添加所选角色
                selectedRole = selectedRole ?? new string[] { };
                selectedRole.Each(roleId =>
                {
                    var userRole = new IdentityUserRole { RoleId = roleId, UserId = user.Id };
                    _db.Set<IdentityUserRole>().Add(userRole);
                });
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            ModelState.AddModelError("", "操作失败。");
            return View();
        }

        //
        //读取用户删除
        // GET: /Users/Delete/5
        [Description("删除用户")]
        public async Task<ActionResult> Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var user = await _userManager.FindByIdAsync(id);
            if (user == null)
            {
                return HttpNotFound();
            }
            var view = Mapper.Map<EditUserRoleViewModel>(user);
            return View(view);
        }
        //
        //写入角色删除
        // POST: /Users/Delete/5
        [Description("删除用户，保存")]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(string id)
        {
            if (ModelState.IsValid)
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                var user = await _userManager.FindByIdAsync(id);
                if (user == null)
                {
                    return HttpNotFound();
                }
                var result = await _userManager.DeleteAsync(user);
                if (!result.Succeeded)
                {
                    ModelState.AddModelError("", result.Errors.First());
                    return View();
                }
                return RedirectToAction("Index");
            }
            return View();
        }

    }
}

AspNetIdentity2Permission.Mvc/Controllers/UsersAdminController.cs
using AspNetIdentity2Permission.Mvc.Models;
using AutoMapper;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web.Mvc;
using Webdiyer.WebControls.Mvc;

namespace AspNetIdentity2Permission.Mvc.Controllers
{

    public class UsersAdminController : BaseController
    {

        // GET: UsersAdmin
        [Description("用户列表")]
        public async Task<ActionResult> Index(int index = 1)
        {
            var users = await _userManager.Users.ToListAsync();
            var views = new List<EditUserViewModel>();
            foreach (var user in users)
            {
                var view = Mapper.Map<EditUserViewModel>(user);
                views.Add(view);
            }
            return View(views.ToPagedList(index, 10));
        }

        //
        //异步读取用户详情
        //GET: /Users/Details/5
        [Description("用户详情")]
        public async Task<ActionResult> Details(string id)
        {
            //用户为空时返回400错误
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            //按Id查找用户
            var user = await _userManager.FindByIdAsync(id);
            var view = Mapper.Map<EditUserViewModel>(user);
            ViewBag.RoleNames = await _userManager.GetRolesAsync(user.Id);

            return View(view);
        }

        //
        //异步读取用户创建
        //GET:/Users/Create
        [Description("新建用户")]
        public async Task<ActionResult> Create()
        {
            //读取角色列表
            ViewBag.RoleId = new SelectList(await _roleManager.Roles.ToListAsync(), "Name", "Name");
            return View();
        }
        //
        //异步写入用户创建
        // POST: /Users/Create
        [Description("新建用户，保存")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(RegisterViewModel userViewModel, params  string[] selectedRoles)
        {
            if (ModelState.IsValid)
            {
                var user = Mapper.Map<ApplicationUser>(userViewModel);
                var adminResult = await _userManager.CreateAsync(user, userViewModel.Password);

                //
                if (adminResult.Succeeded)
                {
                    if (selectedRoles != null)
                    {
                        var result = await _userManager.AddToRolesAsync(user.Id, selectedRoles);
                        if (!result.Succeeded)
                        {
                            ModelState.AddModelError("", result.Errors.First());
                            ViewBag.RoleId = new SelectList(await _roleManager.Roles.ToListAsync(), "Name", "Name");
                            return View();
                        }
                    }
                }
                else
                {
                    ModelState.AddModelError("", adminResult.Errors.First());
                    ViewBag.RoleId = new SelectList(_roleManager.Roles, "Name", "Name");
                    return View();
                }
                return RedirectToAction("Index");
            }
            ViewBag.RoleId = new SelectList(_roleManager.Roles, "Name", "Name");
            return View();
        }

        //
        //读取用户编辑
        // GET: /Users/Edit/1
        [Description("编辑用户")]
        public async Task<ActionResult> Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var user = await _userManager.FindByIdAsync(id);
            if (user == null)
            {
                return HttpNotFound();
            }
            var userRoles = await _userManager.GetRolesAsync(user.Id);
            var view = Mapper.Map<EditUserViewModel>(user);
            view.RolesList = _roleManager.Roles.ToList().Select(x => new SelectListItem()
                {
                    Selected = userRoles.Contains(x.Name),
                    Text = x.Name,
                    Value = x.Name
                });
            return View(view);
        }
        //
        //写入用户编辑
        // POST: /Users/Edit/5
        [Description("编辑用户，保存")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "UserName,Email,Id")]EditUserViewModel editUser, params string[] selectedRole)
        {
            if (ModelState.IsValid)
            {
                var user = await _userManager.FindByIdAsync(editUser.Id);
                if (user == null)
                {
                    return HttpNotFound();
                }
                //不允许修改用户名
                user.Email = editUser.Email;
                //更新用户信息
                var result = await _userManager.UpdateAsync(user);
                if (!result.Succeeded)
                {
                    ModelState.AddModelError("", result.Errors.First());
                    return View();
                }
                //更新角色
                var userRoles = await _userManager.GetRolesAsync(user.Id);
                selectedRole = selectedRole ?? new string[] { };
                result = await _userManager.AddToRolesAsync(user.Id, selectedRole.Except(userRoles).ToArray<string>());
                if (!result.Succeeded)
                {
                    ModelState.AddModelError("", result.Errors.First());
                    return View();
                }
                return RedirectToAction("Index");
            }
            ModelState.AddModelError("", "操作失败。");
            return View();
        }

        //
        //读取用户删除
        // GET: /Users/Delete/5
        [Description("删除用户")]
        public async Task<ActionResult> Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var user = await _userManager.FindByIdAsync(id);
            if (user == null)
            {
                return HttpNotFound();
            }
            var view = Mapper.Map<EditUserViewModel>(user);
            return View(view);
        }
        //
        //写入角色删除
        // POST: /Users/Delete/5
        [Description("删除用户，保存")]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(string id)
        {
            if (ModelState.IsValid)
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                var user = await _userManager.FindByIdAsync(id);
                if (user == null)
                {
                    return HttpNotFound();
                }
                var result = await _userManager.DeleteAsync(user);
                if (!result.Succeeded)
                {
                    ModelState.AddModelError("", result.Errors.First());
                    return View();
                }
                return RedirectToAction("Index");
            }
            return View();
        }

    }
}

AspNetIdentity2Permission.Mvc/Areas/SuperAdmin/Views/UserRole/Create.cshtml
@model AspNetIdentity2Permission.Mvc.Models.RegisterViewModel
@{
    ViewBag.Title = "创建用户";
}

<h2>创建用户</h2>
@using (Html.BeginForm("Create", "UsersAdmin", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
{
    @Html.AntiForgeryToken()
    //创建防伪标记
    <h4>创建用户</h4>
    <hr />
    @Html.ValidationSummary("", new { @class = "text-error" })
    <div class="form-group">
        @Html.LabelFor(m => m.Username, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.Username, new { @class = "form-control" })
        </div>
    </div>
    <div class=" form-group">
        @Html.LabelFor(model => model.Email, new { @class = "col-md-2 control-label" })
        <div class=" col-md-10">
            @Html.TextBoxFor(model => model.Email, new { @class = "form-control" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.Password, new { @class = "col-md-2 control-label" })
        <div class=" col-md-10">
            @Html.PasswordFor(model => model.Password, new { @class = "form-control" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.ConfirmPassword, new { @class = "col-md-2 control-label" })
        <div class=" col-md-10">
            @Html.PasswordFor(model => model.ConfirmPassword, new { @class = "form-control" })
        </div>
    </div>
    <div class=" form-group">
        <label class=" col-md-2 control-label">
            编辑用户角色
        </label>
        <div class=" col-md-10">
            @foreach (var item in (SelectList)ViewBag.RoleId)
            {
                <input type="checkbox" name="SelectedRoles" value="@item.Value" class="checkbox-inline" />
                @Html.Label(item.Value, new { @class = "control-label" })
            }
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="新建用户" class="btn btn-primary" />
        </div>
    </div>
}

<div>
    @Html.ActionLink("返回用户列表", "Index")
</div>

@section Scripts{
    @Scripts.Render("~/bundles/jqueryval")
}

AspNetIdentity2Permission.Mvc/Areas/SuperAdmin/Views/UserRole/Delete.cshtml
@model AspNetIdentity2Permission.Mvc.Models.EditUserRoleViewModel
@{
    ViewBag.Title = "删除用户";
}

<h2>删除用户</h2>
<h3>您确认要删除这个用户吗？？</h3>
<div>
    <h4>用户</h4>
    <hr />
    <dl class=" dl-horizontal ">
        <dt>
            @Html.DisplayNameFor(model => model.UserName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UserName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>
    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        <div class="form-actions no-color">
            <input type="submit" value="删除用户" class=" btn btn-danger" /> |
            @Html.ActionLink("返回用户列表", "Index")
        </div>
    }
</div>

AspNetIdentity2Permission.Mvc/Areas/SuperAdmin/Views/UserRole/Details.cshtml
@model AspNetIdentity2Permission.Mvc.Models.EditUserRoleViewModel
@{
    ViewBag.Title = "用户详情";
}

<h2>用户详情</h2>

<div>
    <h4>用户</h4>
    <hr />
    <dl class="dl-horizontal ">
        <dt>
            @Html.DisplayNameFor(model => model.UserName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.UserName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>
    </dl>
</div>
<h4>该用户所在的角色：</h4>
@if (ViewBag.RoleNames.Count == 0)
{
    <hr />
    <p>这个用户没有设置角色</p>
}
<table class="table">
    @foreach (var item in ViewBag.RoleNames)
    {
        <tr>
            <td>
                @item
            </td>
        </tr>
    }
</table>
<p>
    @Html.ActionLink("编辑用户", "Edit", new { id = Model.Id }, new { @class="btn btn-warning"}) |
    @Html.ActionLink("返回用户列表", "Index")
</p>

AspNetIdentity2Permission.Mvc/Areas/SuperAdmin/Views/UserRole/Edit.cshtml
@model AspNetIdentity2Permission.Mvc.Models.EditUserRoleViewModel
@{
    ViewBag.Title = "编辑用户";
}

<h2>编辑用户</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken();
    <div class=" form-horizontal">
        <h4>编辑用户</h4>
        <hr />
        @Html.ValidationSummary(true)
        @Html.HiddenFor(model => model.Id)
        <div class="form-group">
            @Html.LabelFor(m => m.UserName, new { @class = "col-md-2 control-label" })
            <div class="col-md-10">
                @Html.TextBoxFor(m => m.UserName, new { @class = "form-control",@readonly="readonly" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Email, new { @class = "control-label col-md-2" })
            <div class=" col-md-10">
                @Html.TextBoxFor(model => model.Email, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Email)
            </div>
        </div>
        <div class=" form-group">
            @Html.Label("角色组", new { @class = "control-label col-md-2" })
            <span class=" col-md-10">
                @foreach (var item in Model.RolesList)
                {
                    <input type="checkbox" name="SelectedRole" value="@item.Value" checked="@item.Selected" class="checkbox-inline" />
                    @Html.Label(item.Text, new { @class = "control-label" })
                }
            </span>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="保存" class="btn btn-primary">
            </div>
        </div>
    </div>

}
<div>
    @Html.ActionLink("返回用户列表", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

AspNetIdentity2Permission.Mvc/Areas/SuperAdmin/Views/UserRole/Index.cshtml
@using Webdiyer.WebControls.Mvc

@model IPagedList<AspNetIdentity2Permission.Mvc.Models.EditUserRoleViewModel>
@{
    ViewBag.Title = "用户列表";
}

<h2>用户列表</h2>


<p>
    @Html.ActionLink("新建用户", "Create")
</p>

<div id="views">

    <table class="table table-hover table-striped">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.UserName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Email)
            </th>
            <th></th>

        </tr>


        @foreach (var item in Model)
    {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.UserName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Email)
                </td>
                <td>
                    @Html.ActionLink("编辑用户", "Edit", new { id = item.Id }) |
                    @Html.ActionLink("用户详情", "Details", new { id = item.Id })|
                    @Html.ActionLink("删除用户", "Delete", new { id = item.Id })
                </td>
            </tr>
    }
    </table>

    @Ajax.Pager(Model, new PagerOptions { PageIndexParameterName = "index" }, new MvcAjaxOptions { UpdateTargetId = "views", EnablePartialLoading = true })
</div>
@section Scripts{@{Html.RegisterMvcPagerScriptResource();}}